/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-vercel-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  serial,
  varchar,
  boolean,
  timestamp,
  text,
  jsonb,
  numeric,
  type AnyPgColumn,
  pgEnum,
} from "@payloadcms/db-vercel-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-vercel-postgres/drizzle";
export const enum__locales = pgEnum("enum__locales", ["en", "de", "fr", "it"]);
export const enum_users_role = pgEnum("enum_users_role", [
  "admin",
  "user",
  "publisher",
]);
export const enum_admin_invitations_role = pgEnum(
  "enum_admin_invitations_role",
  ["admin", "user", "publisher"],
);
export const enum_pages_hero_links_link_type = pgEnum(
  "enum_pages_hero_links_link_type",
  ["reference", "custom"],
);
export const enum_pages_hero_links_link_appearance = pgEnum(
  "enum_pages_hero_links_link_appearance",
  ["default", "outline"],
);
export const enum_pages_blocks_cta_links_link_type = pgEnum(
  "enum_pages_blocks_cta_links_link_type",
  ["reference", "custom"],
);
export const enum_pages_blocks_cta_links_link_appearance = pgEnum(
  "enum_pages_blocks_cta_links_link_appearance",
  ["default", "outline"],
);
export const enum_pages_blocks_content_columns_size = pgEnum(
  "enum_pages_blocks_content_columns_size",
  ["oneThird", "half", "twoThirds", "full"],
);
export const enum_pages_blocks_content_columns_link_type = pgEnum(
  "enum_pages_blocks_content_columns_link_type",
  ["reference", "custom"],
);
export const enum_pages_blocks_content_columns_link_appearance = pgEnum(
  "enum_pages_blocks_content_columns_link_appearance",
  ["default", "outline"],
);
export const enum_pages_blocks_banner_style = pgEnum(
  "enum_pages_blocks_banner_style",
  ["info", "warning", "error", "success"],
);
export const enum_pages_hero_type = pgEnum("enum_pages_hero_type", [
  "none",
  "highImpact",
  "mediumImpact",
  "lowImpact",
]);
export const enum_pages_status = pgEnum("enum_pages_status", [
  "draft",
  "published",
]);
export const enum__pages_v_version_hero_links_link_type = pgEnum(
  "enum__pages_v_version_hero_links_link_type",
  ["reference", "custom"],
);
export const enum__pages_v_version_hero_links_link_appearance = pgEnum(
  "enum__pages_v_version_hero_links_link_appearance",
  ["default", "outline"],
);
export const enum__pages_v_blocks_cta_links_link_type = pgEnum(
  "enum__pages_v_blocks_cta_links_link_type",
  ["reference", "custom"],
);
export const enum__pages_v_blocks_cta_links_link_appearance = pgEnum(
  "enum__pages_v_blocks_cta_links_link_appearance",
  ["default", "outline"],
);
export const enum__pages_v_blocks_content_columns_size = pgEnum(
  "enum__pages_v_blocks_content_columns_size",
  ["oneThird", "half", "twoThirds", "full"],
);
export const enum__pages_v_blocks_content_columns_link_type = pgEnum(
  "enum__pages_v_blocks_content_columns_link_type",
  ["reference", "custom"],
);
export const enum__pages_v_blocks_content_columns_link_appearance = pgEnum(
  "enum__pages_v_blocks_content_columns_link_appearance",
  ["default", "outline"],
);
export const enum__pages_v_blocks_banner_style = pgEnum(
  "enum__pages_v_blocks_banner_style",
  ["info", "warning", "error", "success"],
);
export const enum__pages_v_version_hero_type = pgEnum(
  "enum__pages_v_version_hero_type",
  ["none", "highImpact", "mediumImpact", "lowImpact"],
);
export const enum__pages_v_version_status = pgEnum(
  "enum__pages_v_version_status",
  ["draft", "published"],
);
export const enum__pages_v_published_locale = pgEnum(
  "enum__pages_v_published_locale",
  ["en", "de", "fr", "it"],
);
export const enum_payload_jobs_log_task_slug = pgEnum(
  "enum_payload_jobs_log_task_slug",
  ["inline", "processPayment", "schedulePublish"],
);
export const enum_payload_jobs_log_state = pgEnum(
  "enum_payload_jobs_log_state",
  ["failed", "succeeded"],
);
export const enum_payload_jobs_task_slug = pgEnum(
  "enum_payload_jobs_task_slug",
  ["inline", "processPayment", "schedulePublish"],
);
export const enum_payload_folders_folder_type = pgEnum(
  "enum_payload_folders_folder_type",
  ["media"],
);
export const enum_header_nav_items_link_type = pgEnum(
  "enum_header_nav_items_link_type",
  ["reference", "custom"],
);
export const enum_footer_nav_items_link_type = pgEnum(
  "enum_footer_nav_items_link_type",
  ["reference", "custom"],
);

export const users_role = pgTable(
  "users_role",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_users_role("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("users_role_order_idx").on(columns.order),
    index("users_role_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [users.id],
      name: "users_role_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    email: varchar("email").notNull(),
    emailVerified: boolean("email_verified").notNull().default(false),
    image: varchar("image"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    banned: boolean("banned").default(false),
    banReason: varchar("ban_reason"),
    banExpires: timestamp("ban_expires", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    uniqueIndex("users_email_idx").on(columns.email),
    index("users_created_at_idx").on(columns.createdAt),
    index("users_updated_at_idx").on(columns.updatedAt),
  ],
);

export const sessions = pgTable(
  "sessions",
  {
    id: serial("id").primaryKey(),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    token: varchar("token").notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    ipAddress: varchar("ip_address"),
    userAgent: varchar("user_agent"),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    impersonatedBy: integer("impersonated_by_id").references(() => users.id, {
      onDelete: "set null",
    }),
  },
  (columns) => [
    uniqueIndex("sessions_token_idx").on(columns.token),
    index("sessions_created_at_idx").on(columns.createdAt),
    index("sessions_updated_at_idx").on(columns.updatedAt),
    index("sessions_user_idx").on(columns.user),
    index("sessions_impersonated_by_idx").on(columns.impersonatedBy),
  ],
);

export const accounts = pgTable(
  "accounts",
  {
    id: serial("id").primaryKey(),
    accountId: varchar("account_id").notNull(),
    providerId: varchar("provider_id").notNull(),
    user: integer("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    accessToken: varchar("access_token"),
    refreshToken: varchar("refresh_token"),
    idToken: varchar("id_token"),
    accessTokenExpiresAt: timestamp("access_token_expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    refreshTokenExpiresAt: timestamp("refresh_token_expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    scope: varchar("scope"),
    password: varchar("password"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("accounts_account_id_idx").on(columns.accountId),
    index("accounts_user_idx").on(columns.user),
    index("accounts_access_token_expires_at_idx").on(
      columns.accessTokenExpiresAt,
    ),
    index("accounts_refresh_token_expires_at_idx").on(
      columns.refreshTokenExpiresAt,
    ),
    index("accounts_created_at_idx").on(columns.createdAt),
    index("accounts_updated_at_idx").on(columns.updatedAt),
  ],
);

export const verifications = pgTable(
  "verifications",
  {
    id: serial("id").primaryKey(),
    identifier: varchar("identifier").notNull(),
    value: varchar("value").notNull(),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("verifications_identifier_idx").on(columns.identifier),
    index("verifications_expires_at_idx").on(columns.expiresAt),
    index("verifications_created_at_idx").on(columns.createdAt),
    index("verifications_updated_at_idx").on(columns.updatedAt),
  ],
);

export const admin_invitations = pgTable(
  "admin_invitations",
  {
    id: serial("id").primaryKey(),
    role: enum_admin_invitations_role("role").notNull().default("admin"),
    token: varchar("token").notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("admin_invitations_token_idx").on(columns.token),
    index("admin_invitations_updated_at_idx").on(columns.updatedAt),
    index("admin_invitations_created_at_idx").on(columns.createdAt),
  ],
);

export const pages_hero_links = pgTable(
  "pages_hero_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    link_type:
      enum_pages_hero_links_link_type("link_type").default("reference"),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label"),
    link_appearance:
      enum_pages_hero_links_link_appearance("link_appearance").default(
        "default",
      ),
  },
  (columns) => [
    index("pages_hero_links_order_idx").on(columns._order),
    index("pages_hero_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_hero_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta_links = pgTable(
  "pages_blocks_cta_links",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    link_type:
      enum_pages_blocks_cta_links_link_type("link_type").default("reference"),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label"),
    link_appearance:
      enum_pages_blocks_cta_links_link_appearance("link_appearance").default(
        "default",
      ),
  },
  (columns) => [
    index("pages_blocks_cta_links_order_idx").on(columns._order),
    index("pages_blocks_cta_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_cta.id],
      name: "pages_blocks_cta_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_cta = pgTable(
  "pages_blocks_cta",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    richText: jsonb("rich_text"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_cta_order_idx").on(columns._order),
    index("pages_blocks_cta_parent_id_idx").on(columns._parentID),
    index("pages_blocks_cta_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_cta_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_content_columns = pgTable(
  "pages_blocks_content_columns",
  {
    _order: integer("_order").notNull(),
    _parentID: varchar("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    size: enum_pages_blocks_content_columns_size("size").default("oneThird"),
    richText: jsonb("rich_text"),
    enableLink: boolean("enable_link"),
    link_type:
      enum_pages_blocks_content_columns_link_type("link_type").default(
        "reference",
      ),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label"),
    link_appearance:
      enum_pages_blocks_content_columns_link_appearance(
        "link_appearance",
      ).default("default"),
  },
  (columns) => [
    index("pages_blocks_content_columns_order_idx").on(columns._order),
    index("pages_blocks_content_columns_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages_blocks_content.id],
      name: "pages_blocks_content_columns_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_content = pgTable(
  "pages_blocks_content",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_content_order_idx").on(columns._order),
    index("pages_blocks_content_parent_id_idx").on(columns._parentID),
    index("pages_blocks_content_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_content_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_media_block = pgTable(
  "pages_blocks_media_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    media: integer("media_id").references(() => media.id, {
      onDelete: "set null",
    }),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_media_block_order_idx").on(columns._order),
    index("pages_blocks_media_block_parent_id_idx").on(columns._parentID),
    index("pages_blocks_media_block_path_idx").on(columns._path),
    index("pages_blocks_media_block_media_idx").on(columns.media),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_media_block_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_blocks_banner = pgTable(
  "pages_blocks_banner",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: varchar("id").primaryKey(),
    style: enum_pages_blocks_banner_style("style").default("info"),
    content: jsonb("content"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("pages_blocks_banner_order_idx").on(columns._order),
    index("pages_blocks_banner_parent_id_idx").on(columns._parentID),
    index("pages_blocks_banner_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_blocks_banner_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages = pgTable(
  "pages",
  {
    id: serial("id").primaryKey(),
    hero_type: enum_pages_hero_type("hero_type").default("lowImpact"),
    hero_richText: jsonb("hero_rich_text"),
    hero_media: integer("hero_media_id").references(() => media.id, {
      onDelete: "set null",
    }),
    publishedAt: timestamp("published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    generateSlug: boolean("generate_slug").default(true),
    slug: varchar("slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    _status: enum_pages_status("_status").default("draft"),
  },
  (columns) => [
    index("pages_hero_hero_media_idx").on(columns.hero_media),
    uniqueIndex("pages_slug_idx").on(columns.slug),
    index("pages_updated_at_idx").on(columns.updatedAt),
    index("pages_created_at_idx").on(columns.createdAt),
    index("pages__status_idx").on(columns._status),
  ],
);

export const pages_locales = pgTable(
  "pages_locales",
  {
    title: varchar("title"),
    meta_title: varchar("meta_title"),
    meta_image: integer("meta_image_id").references(() => media.id, {
      onDelete: "set null",
    }),
    meta_description: varchar("meta_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("pages_meta_meta_image_idx").on(columns.meta_image, columns._locale),
    uniqueIndex("pages_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [pages.id],
      name: "pages_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const pages_rels = pgTable(
  "pages_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: integer("pages_id"),
  },
  (columns) => [
    index("pages_rels_order_idx").on(columns.order),
    index("pages_rels_parent_idx").on(columns.parent),
    index("pages_rels_path_idx").on(columns.path),
    index("pages_rels_pages_id_idx").on(columns.pagesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [pages.id],
      name: "pages_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "pages_rels_pages_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_version_hero_links = pgTable(
  "_pages_v_version_hero_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    link_type:
      enum__pages_v_version_hero_links_link_type("link_type").default(
        "reference",
      ),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label"),
    link_appearance:
      enum__pages_v_version_hero_links_link_appearance(
        "link_appearance",
      ).default("default"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_version_hero_links_order_idx").on(columns._order),
    index("_pages_v_version_hero_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_version_hero_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_cta_links = pgTable(
  "_pages_v_blocks_cta_links",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    link_type:
      enum__pages_v_blocks_cta_links_link_type("link_type").default(
        "reference",
      ),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label"),
    link_appearance:
      enum__pages_v_blocks_cta_links_link_appearance("link_appearance").default(
        "default",
      ),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_blocks_cta_links_order_idx").on(columns._order),
    index("_pages_v_blocks_cta_links_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v_blocks_cta.id],
      name: "_pages_v_blocks_cta_links_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_cta = pgTable(
  "_pages_v_blocks_cta",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    richText: jsonb("rich_text"),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_cta_order_idx").on(columns._order),
    index("_pages_v_blocks_cta_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_cta_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_cta_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_content_columns = pgTable(
  "_pages_v_blocks_content_columns",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: serial("id").primaryKey(),
    size: enum__pages_v_blocks_content_columns_size("size").default("oneThird"),
    richText: jsonb("rich_text"),
    enableLink: boolean("enable_link"),
    link_type:
      enum__pages_v_blocks_content_columns_link_type("link_type").default(
        "reference",
      ),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label"),
    link_appearance:
      enum__pages_v_blocks_content_columns_link_appearance(
        "link_appearance",
      ).default("default"),
    _uuid: varchar("_uuid"),
  },
  (columns) => [
    index("_pages_v_blocks_content_columns_order_idx").on(columns._order),
    index("_pages_v_blocks_content_columns_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v_blocks_content.id],
      name: "_pages_v_blocks_content_columns_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_content = pgTable(
  "_pages_v_blocks_content",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_content_order_idx").on(columns._order),
    index("_pages_v_blocks_content_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_content_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_content_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_media_block = pgTable(
  "_pages_v_blocks_media_block",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    media: integer("media_id").references(() => media.id, {
      onDelete: "set null",
    }),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_media_block_order_idx").on(columns._order),
    index("_pages_v_blocks_media_block_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_media_block_path_idx").on(columns._path),
    index("_pages_v_blocks_media_block_media_idx").on(columns.media),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_media_block_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_blocks_banner = pgTable(
  "_pages_v_blocks_banner",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    _path: text("_path").notNull(),
    id: serial("id").primaryKey(),
    style: enum__pages_v_blocks_banner_style("style").default("info"),
    content: jsonb("content"),
    _uuid: varchar("_uuid"),
    blockName: varchar("block_name"),
  },
  (columns) => [
    index("_pages_v_blocks_banner_order_idx").on(columns._order),
    index("_pages_v_blocks_banner_parent_id_idx").on(columns._parentID),
    index("_pages_v_blocks_banner_path_idx").on(columns._path),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_blocks_banner_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v = pgTable(
  "_pages_v",
  {
    id: serial("id").primaryKey(),
    parent: integer("parent_id").references(() => pages.id, {
      onDelete: "set null",
    }),
    version_hero_type:
      enum__pages_v_version_hero_type("version_hero_type").default("lowImpact"),
    version_hero_richText: jsonb("version_hero_rich_text"),
    version_hero_media: integer("version_hero_media_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_publishedAt: timestamp("version_published_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_generateSlug: boolean("version_generate_slug").default(true),
    version_slug: varchar("version_slug"),
    version_updatedAt: timestamp("version_updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version_createdAt: timestamp("version_created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    version__status:
      enum__pages_v_version_status("version__status").default("draft"),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    snapshot: boolean("snapshot"),
    publishedLocale: enum__pages_v_published_locale("published_locale"),
    latest: boolean("latest"),
    autosave: boolean("autosave"),
  },
  (columns) => [
    index("_pages_v_parent_idx").on(columns.parent),
    index("_pages_v_version_hero_version_hero_media_idx").on(
      columns.version_hero_media,
    ),
    index("_pages_v_version_version_slug_idx").on(columns.version_slug),
    index("_pages_v_version_version_updated_at_idx").on(
      columns.version_updatedAt,
    ),
    index("_pages_v_version_version_created_at_idx").on(
      columns.version_createdAt,
    ),
    index("_pages_v_version_version__status_idx").on(columns.version__status),
    index("_pages_v_created_at_idx").on(columns.createdAt),
    index("_pages_v_updated_at_idx").on(columns.updatedAt),
    index("_pages_v_snapshot_idx").on(columns.snapshot),
    index("_pages_v_published_locale_idx").on(columns.publishedLocale),
    index("_pages_v_latest_idx").on(columns.latest),
    index("_pages_v_autosave_idx").on(columns.autosave),
  ],
);

export const _pages_v_locales = pgTable(
  "_pages_v_locales",
  {
    version_title: varchar("version_title"),
    version_meta_title: varchar("version_meta_title"),
    version_meta_image: integer("version_meta_image_id").references(
      () => media.id,
      {
        onDelete: "set null",
      },
    ),
    version_meta_description: varchar("version_meta_description"),
    id: serial("id").primaryKey(),
    _locale: enum__locales("_locale").notNull(),
    _parentID: integer("_parent_id").notNull(),
  },
  (columns) => [
    index("_pages_v_version_meta_version_meta_image_idx").on(
      columns.version_meta_image,
      columns._locale,
    ),
    uniqueIndex("_pages_v_locales_locale_parent_id_unique").on(
      columns._locale,
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_locales_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const _pages_v_rels = pgTable(
  "_pages_v_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: integer("pages_id"),
  },
  (columns) => [
    index("_pages_v_rels_order_idx").on(columns.order),
    index("_pages_v_rels_parent_idx").on(columns.parent),
    index("_pages_v_rels_path_idx").on(columns.path),
    index("_pages_v_rels_pages_id_idx").on(columns.pagesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [_pages_v.id],
      name: "_pages_v_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "_pages_v_rels_pages_fk",
    }).onDelete("cascade"),
  ],
);

export const media = pgTable(
  "media",
  {
    id: serial("id").primaryKey(),
    alt: varchar("alt"),
    caption: jsonb("caption"),
    placeholder: varchar("placeholder"),
    folder: integer("folder_id").references(() => payload_folders.id, {
      onDelete: "set null",
    }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    url: varchar("url"),
    thumbnailURL: varchar("thumbnail_u_r_l"),
    filename: varchar("filename"),
    mimeType: varchar("mime_type"),
    filesize: numeric("filesize", { mode: "number" }),
    width: numeric("width", { mode: "number" }),
    height: numeric("height", { mode: "number" }),
    focalX: numeric("focal_x", { mode: "number" }),
    focalY: numeric("focal_y", { mode: "number" }),
    sizes_thumbnail_url: varchar("sizes_thumbnail_url"),
    sizes_thumbnail_width: numeric("sizes_thumbnail_width", { mode: "number" }),
    sizes_thumbnail_height: numeric("sizes_thumbnail_height", {
      mode: "number",
    }),
    sizes_thumbnail_mimeType: varchar("sizes_thumbnail_mime_type"),
    sizes_thumbnail_filesize: numeric("sizes_thumbnail_filesize", {
      mode: "number",
    }),
    sizes_thumbnail_filename: varchar("sizes_thumbnail_filename"),
    sizes_square_url: varchar("sizes_square_url"),
    sizes_square_width: numeric("sizes_square_width", { mode: "number" }),
    sizes_square_height: numeric("sizes_square_height", { mode: "number" }),
    sizes_square_mimeType: varchar("sizes_square_mime_type"),
    sizes_square_filesize: numeric("sizes_square_filesize", { mode: "number" }),
    sizes_square_filename: varchar("sizes_square_filename"),
    sizes_small_url: varchar("sizes_small_url"),
    sizes_small_width: numeric("sizes_small_width", { mode: "number" }),
    sizes_small_height: numeric("sizes_small_height", { mode: "number" }),
    sizes_small_mimeType: varchar("sizes_small_mime_type"),
    sizes_small_filesize: numeric("sizes_small_filesize", { mode: "number" }),
    sizes_small_filename: varchar("sizes_small_filename"),
    sizes_medium_url: varchar("sizes_medium_url"),
    sizes_medium_width: numeric("sizes_medium_width", { mode: "number" }),
    sizes_medium_height: numeric("sizes_medium_height", { mode: "number" }),
    sizes_medium_mimeType: varchar("sizes_medium_mime_type"),
    sizes_medium_filesize: numeric("sizes_medium_filesize", { mode: "number" }),
    sizes_medium_filename: varchar("sizes_medium_filename"),
    sizes_large_url: varchar("sizes_large_url"),
    sizes_large_width: numeric("sizes_large_width", { mode: "number" }),
    sizes_large_height: numeric("sizes_large_height", { mode: "number" }),
    sizes_large_mimeType: varchar("sizes_large_mime_type"),
    sizes_large_filesize: numeric("sizes_large_filesize", { mode: "number" }),
    sizes_large_filename: varchar("sizes_large_filename"),
    sizes_xlarge_url: varchar("sizes_xlarge_url"),
    sizes_xlarge_width: numeric("sizes_xlarge_width", { mode: "number" }),
    sizes_xlarge_height: numeric("sizes_xlarge_height", { mode: "number" }),
    sizes_xlarge_mimeType: varchar("sizes_xlarge_mime_type"),
    sizes_xlarge_filesize: numeric("sizes_xlarge_filesize", { mode: "number" }),
    sizes_xlarge_filename: varchar("sizes_xlarge_filename"),
    sizes_og_url: varchar("sizes_og_url"),
    sizes_og_width: numeric("sizes_og_width", { mode: "number" }),
    sizes_og_height: numeric("sizes_og_height", { mode: "number" }),
    sizes_og_mimeType: varchar("sizes_og_mime_type"),
    sizes_og_filesize: numeric("sizes_og_filesize", { mode: "number" }),
    sizes_og_filename: varchar("sizes_og_filename"),
  },
  (columns) => [
    index("media_folder_idx").on(columns.folder),
    index("media_updated_at_idx").on(columns.updatedAt),
    index("media_created_at_idx").on(columns.createdAt),
    uniqueIndex("media_filename_idx").on(columns.filename),
    index("media_sizes_thumbnail_sizes_thumbnail_filename_idx").on(
      columns.sizes_thumbnail_filename,
    ),
    index("media_sizes_square_sizes_square_filename_idx").on(
      columns.sizes_square_filename,
    ),
    index("media_sizes_small_sizes_small_filename_idx").on(
      columns.sizes_small_filename,
    ),
    index("media_sizes_medium_sizes_medium_filename_idx").on(
      columns.sizes_medium_filename,
    ),
    index("media_sizes_large_sizes_large_filename_idx").on(
      columns.sizes_large_filename,
    ),
    index("media_sizes_xlarge_sizes_xlarge_filename_idx").on(
      columns.sizes_xlarge_filename,
    ),
    index("media_sizes_og_sizes_og_filename_idx").on(columns.sizes_og_filename),
  ],
);

export const panter_translate = pgTable(
  "panter_translate",
  {
    id: serial("id").primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("panter_translate_updated_at_idx").on(columns.updatedAt),
    index("panter_translate_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: serial("id").primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_jobs_log = pgTable(
  "payload_jobs_log",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    executedAt: timestamp("executed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    taskSlug: enum_payload_jobs_log_task_slug("task_slug").notNull(),
    taskID: varchar("task_i_d").notNull(),
    input: jsonb("input"),
    output: jsonb("output"),
    state: enum_payload_jobs_log_state("state").notNull(),
    error: jsonb("error"),
  },
  (columns) => [
    index("payload_jobs_log_order_idx").on(columns._order),
    index("payload_jobs_log_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [payload_jobs.id],
      name: "payload_jobs_log_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_jobs = pgTable(
  "payload_jobs",
  {
    id: serial("id").primaryKey(),
    input: jsonb("input"),
    completedAt: timestamp("completed_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    totalTried: numeric("total_tried", { mode: "number" }).default(0),
    hasError: boolean("has_error").default(false),
    error: jsonb("error"),
    taskSlug: enum_payload_jobs_task_slug("task_slug"),
    queue: varchar("queue").default("default"),
    waitUntil: timestamp("wait_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    processing: boolean("processing").default(false),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_jobs_completed_at_idx").on(columns.completedAt),
    index("payload_jobs_total_tried_idx").on(columns.totalTried),
    index("payload_jobs_has_error_idx").on(columns.hasError),
    index("payload_jobs_task_slug_idx").on(columns.taskSlug),
    index("payload_jobs_queue_idx").on(columns.queue),
    index("payload_jobs_wait_until_idx").on(columns.waitUntil),
    index("payload_jobs_processing_idx").on(columns.processing),
    index("payload_jobs_updated_at_idx").on(columns.updatedAt),
    index("payload_jobs_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_folders_folder_type = pgTable(
  "payload_folders_folder_type",
  {
    order: integer("order").notNull(),
    parent: integer("parent_id").notNull(),
    value: enum_payload_folders_folder_type("value"),
    id: serial("id").primaryKey(),
  },
  (columns) => [
    index("payload_folders_folder_type_order_idx").on(columns.order),
    index("payload_folders_folder_type_parent_idx").on(columns.parent),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_folders.id],
      name: "payload_folders_folder_type_parent_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_folders = pgTable(
  "payload_folders",
  {
    id: serial("id").primaryKey(),
    name: varchar("name").notNull(),
    folder: integer("folder_id").references(
      (): AnyPgColumn => payload_folders.id,
      {
        onDelete: "set null",
      },
    ),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_folders_name_idx").on(columns.name),
    index("payload_folders_folder_idx").on(columns.folder),
    index("payload_folders_updated_at_idx").on(columns.updatedAt),
    index("payload_folders_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: serial("id").primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
    sessionsID: integer("sessions_id"),
    accountsID: integer("accounts_id"),
    verificationsID: integer("verifications_id"),
    "admin-invitationsID": integer("admin_invitations_id"),
    pagesID: integer("pages_id"),
    mediaID: integer("media_id"),
    "panter-translateID": integer("panter_translate_id"),
    "payload-foldersID": integer("payload_folders_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_sessions_id_idx").on(
      columns.sessionsID,
    ),
    index("payload_locked_documents_rels_accounts_id_idx").on(
      columns.accountsID,
    ),
    index("payload_locked_documents_rels_verifications_id_idx").on(
      columns.verificationsID,
    ),
    index("payload_locked_documents_rels_admin_invitations_id_idx").on(
      columns["admin-invitationsID"],
    ),
    index("payload_locked_documents_rels_pages_id_idx").on(columns.pagesID),
    index("payload_locked_documents_rels_media_id_idx").on(columns.mediaID),
    index("payload_locked_documents_rels_panter_translate_id_idx").on(
      columns["panter-translateID"],
    ),
    index("payload_locked_documents_rels_payload_folders_id_idx").on(
      columns["payload-foldersID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["sessionsID"]],
      foreignColumns: [sessions.id],
      name: "payload_locked_documents_rels_sessions_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["accountsID"]],
      foreignColumns: [accounts.id],
      name: "payload_locked_documents_rels_accounts_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["verificationsID"]],
      foreignColumns: [verifications.id],
      name: "payload_locked_documents_rels_verifications_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["admin-invitationsID"]],
      foreignColumns: [admin_invitations.id],
      name: "payload_locked_documents_rels_admin_invitations_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "payload_locked_documents_rels_pages_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["mediaID"]],
      foreignColumns: [media.id],
      name: "payload_locked_documents_rels_media_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["panter-translateID"]],
      foreignColumns: [panter_translate.id],
      name: "payload_locked_documents_rels_panter_translate_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["payload-foldersID"]],
      foreignColumns: [payload_folders.id],
      name: "payload_locked_documents_rels_payload_folders_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: serial("id").primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: integer("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: serial("id").primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const header_nav_items = pgTable(
  "header_nav_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    link_type:
      enum_header_nav_items_link_type("link_type").default("reference"),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label").notNull(),
  },
  (columns) => [
    index("header_nav_items_order_idx").on(columns._order),
    index("header_nav_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [header.id],
      name: "header_nav_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const header = pgTable("header", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const header_rels = pgTable(
  "header_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: integer("pages_id"),
  },
  (columns) => [
    index("header_rels_order_idx").on(columns.order),
    index("header_rels_parent_idx").on(columns.parent),
    index("header_rels_path_idx").on(columns.path),
    index("header_rels_pages_id_idx").on(columns.pagesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [header.id],
      name: "header_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "header_rels_pages_fk",
    }).onDelete("cascade"),
  ],
);

export const footer_nav_items = pgTable(
  "footer_nav_items",
  {
    _order: integer("_order").notNull(),
    _parentID: integer("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    link_type:
      enum_footer_nav_items_link_type("link_type").default("reference"),
    link_newTab: boolean("link_new_tab"),
    link_url: varchar("link_url"),
    link_label: varchar("link_label").notNull(),
  },
  (columns) => [
    index("footer_nav_items_order_idx").on(columns._order),
    index("footer_nav_items_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [footer.id],
      name: "footer_nav_items_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const footer = pgTable("footer", {
  id: serial("id").primaryKey(),
  updatedAt: timestamp("updated_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
  createdAt: timestamp("created_at", {
    mode: "string",
    withTimezone: true,
    precision: 3,
  }),
});

export const footer_rels = pgTable(
  "footer_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: integer("parent_id").notNull(),
    path: varchar("path").notNull(),
    pagesID: integer("pages_id"),
  },
  (columns) => [
    index("footer_rels_order_idx").on(columns.order),
    index("footer_rels_parent_idx").on(columns.parent),
    index("footer_rels_path_idx").on(columns.path),
    index("footer_rels_pages_id_idx").on(columns.pagesID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [footer.id],
      name: "footer_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["pagesID"]],
      foreignColumns: [pages.id],
      name: "footer_rels_pages_fk",
    }).onDelete("cascade"),
  ],
);

export const relations_users_role = relations(users_role, ({ one }) => ({
  parent: one(users, {
    fields: [users_role.parent],
    references: [users.id],
    relationName: "role",
  }),
}));
export const relations_users = relations(users, ({ many }) => ({
  role: many(users_role, {
    relationName: "role",
  }),
}));
export const relations_sessions = relations(sessions, ({ one }) => ({
  user: one(users, {
    fields: [sessions.user],
    references: [users.id],
    relationName: "user",
  }),
  impersonatedBy: one(users, {
    fields: [sessions.impersonatedBy],
    references: [users.id],
    relationName: "impersonatedBy",
  }),
}));
export const relations_accounts = relations(accounts, ({ one }) => ({
  user: one(users, {
    fields: [accounts.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_verifications = relations(verifications, () => ({}));
export const relations_admin_invitations = relations(
  admin_invitations,
  () => ({}),
);
export const relations_pages_hero_links = relations(
  pages_hero_links,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_hero_links._parentID],
      references: [pages.id],
      relationName: "hero_links",
    }),
  }),
);
export const relations_pages_blocks_cta_links = relations(
  pages_blocks_cta_links,
  ({ one }) => ({
    _parentID: one(pages_blocks_cta, {
      fields: [pages_blocks_cta_links._parentID],
      references: [pages_blocks_cta.id],
      relationName: "links",
    }),
  }),
);
export const relations_pages_blocks_cta = relations(
  pages_blocks_cta,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_cta._parentID],
      references: [pages.id],
      relationName: "_blocks_cta",
    }),
    links: many(pages_blocks_cta_links, {
      relationName: "links",
    }),
  }),
);
export const relations_pages_blocks_content_columns = relations(
  pages_blocks_content_columns,
  ({ one }) => ({
    _parentID: one(pages_blocks_content, {
      fields: [pages_blocks_content_columns._parentID],
      references: [pages_blocks_content.id],
      relationName: "columns",
    }),
  }),
);
export const relations_pages_blocks_content = relations(
  pages_blocks_content,
  ({ one, many }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_content._parentID],
      references: [pages.id],
      relationName: "_blocks_content",
    }),
    columns: many(pages_blocks_content_columns, {
      relationName: "columns",
    }),
  }),
);
export const relations_pages_blocks_media_block = relations(
  pages_blocks_media_block,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_media_block._parentID],
      references: [pages.id],
      relationName: "_blocks_mediaBlock",
    }),
    media: one(media, {
      fields: [pages_blocks_media_block.media],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations_pages_blocks_banner = relations(
  pages_blocks_banner,
  ({ one }) => ({
    _parentID: one(pages, {
      fields: [pages_blocks_banner._parentID],
      references: [pages.id],
      relationName: "_blocks_banner",
    }),
  }),
);
export const relations_pages_locales = relations(pages_locales, ({ one }) => ({
  _parentID: one(pages, {
    fields: [pages_locales._parentID],
    references: [pages.id],
    relationName: "_locales",
  }),
  meta_image: one(media, {
    fields: [pages_locales.meta_image],
    references: [media.id],
    relationName: "meta_image",
  }),
}));
export const relations_pages_rels = relations(pages_rels, ({ one }) => ({
  parent: one(pages, {
    fields: [pages_rels.parent],
    references: [pages.id],
    relationName: "_rels",
  }),
  pagesID: one(pages, {
    fields: [pages_rels.pagesID],
    references: [pages.id],
    relationName: "pages",
  }),
}));
export const relations_pages = relations(pages, ({ one, many }) => ({
  hero_links: many(pages_hero_links, {
    relationName: "hero_links",
  }),
  hero_media: one(media, {
    fields: [pages.hero_media],
    references: [media.id],
    relationName: "hero_media",
  }),
  _blocks_cta: many(pages_blocks_cta, {
    relationName: "_blocks_cta",
  }),
  _blocks_content: many(pages_blocks_content, {
    relationName: "_blocks_content",
  }),
  _blocks_mediaBlock: many(pages_blocks_media_block, {
    relationName: "_blocks_mediaBlock",
  }),
  _blocks_banner: many(pages_blocks_banner, {
    relationName: "_blocks_banner",
  }),
  _locales: many(pages_locales, {
    relationName: "_locales",
  }),
  _rels: many(pages_rels, {
    relationName: "_rels",
  }),
}));
export const relations__pages_v_version_hero_links = relations(
  _pages_v_version_hero_links,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_version_hero_links._parentID],
      references: [_pages_v.id],
      relationName: "version_hero_links",
    }),
  }),
);
export const relations__pages_v_blocks_cta_links = relations(
  _pages_v_blocks_cta_links,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_cta, {
      fields: [_pages_v_blocks_cta_links._parentID],
      references: [_pages_v_blocks_cta.id],
      relationName: "links",
    }),
  }),
);
export const relations__pages_v_blocks_cta = relations(
  _pages_v_blocks_cta,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_cta._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_cta",
    }),
    links: many(_pages_v_blocks_cta_links, {
      relationName: "links",
    }),
  }),
);
export const relations__pages_v_blocks_content_columns = relations(
  _pages_v_blocks_content_columns,
  ({ one }) => ({
    _parentID: one(_pages_v_blocks_content, {
      fields: [_pages_v_blocks_content_columns._parentID],
      references: [_pages_v_blocks_content.id],
      relationName: "columns",
    }),
  }),
);
export const relations__pages_v_blocks_content = relations(
  _pages_v_blocks_content,
  ({ one, many }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_content._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_content",
    }),
    columns: many(_pages_v_blocks_content_columns, {
      relationName: "columns",
    }),
  }),
);
export const relations__pages_v_blocks_media_block = relations(
  _pages_v_blocks_media_block,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_media_block._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_mediaBlock",
    }),
    media: one(media, {
      fields: [_pages_v_blocks_media_block.media],
      references: [media.id],
      relationName: "media",
    }),
  }),
);
export const relations__pages_v_blocks_banner = relations(
  _pages_v_blocks_banner,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_blocks_banner._parentID],
      references: [_pages_v.id],
      relationName: "_blocks_banner",
    }),
  }),
);
export const relations__pages_v_locales = relations(
  _pages_v_locales,
  ({ one }) => ({
    _parentID: one(_pages_v, {
      fields: [_pages_v_locales._parentID],
      references: [_pages_v.id],
      relationName: "_locales",
    }),
    version_meta_image: one(media, {
      fields: [_pages_v_locales.version_meta_image],
      references: [media.id],
      relationName: "version_meta_image",
    }),
  }),
);
export const relations__pages_v_rels = relations(_pages_v_rels, ({ one }) => ({
  parent: one(_pages_v, {
    fields: [_pages_v_rels.parent],
    references: [_pages_v.id],
    relationName: "_rels",
  }),
  pagesID: one(pages, {
    fields: [_pages_v_rels.pagesID],
    references: [pages.id],
    relationName: "pages",
  }),
}));
export const relations__pages_v = relations(_pages_v, ({ one, many }) => ({
  parent: one(pages, {
    fields: [_pages_v.parent],
    references: [pages.id],
    relationName: "parent",
  }),
  version_hero_links: many(_pages_v_version_hero_links, {
    relationName: "version_hero_links",
  }),
  version_hero_media: one(media, {
    fields: [_pages_v.version_hero_media],
    references: [media.id],
    relationName: "version_hero_media",
  }),
  _blocks_cta: many(_pages_v_blocks_cta, {
    relationName: "_blocks_cta",
  }),
  _blocks_content: many(_pages_v_blocks_content, {
    relationName: "_blocks_content",
  }),
  _blocks_mediaBlock: many(_pages_v_blocks_media_block, {
    relationName: "_blocks_mediaBlock",
  }),
  _blocks_banner: many(_pages_v_blocks_banner, {
    relationName: "_blocks_banner",
  }),
  _locales: many(_pages_v_locales, {
    relationName: "_locales",
  }),
  _rels: many(_pages_v_rels, {
    relationName: "_rels",
  }),
}));
export const relations_media = relations(media, ({ one }) => ({
  folder: one(payload_folders, {
    fields: [media.folder],
    references: [payload_folders.id],
    relationName: "folder",
  }),
}));
export const relations_panter_translate = relations(
  panter_translate,
  () => ({}),
);
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_jobs_log = relations(
  payload_jobs_log,
  ({ one }) => ({
    _parentID: one(payload_jobs, {
      fields: [payload_jobs_log._parentID],
      references: [payload_jobs.id],
      relationName: "log",
    }),
  }),
);
export const relations_payload_jobs = relations(payload_jobs, ({ many }) => ({
  log: many(payload_jobs_log, {
    relationName: "log",
  }),
}));
export const relations_payload_folders_folder_type = relations(
  payload_folders_folder_type,
  ({ one }) => ({
    parent: one(payload_folders, {
      fields: [payload_folders_folder_type.parent],
      references: [payload_folders.id],
      relationName: "folderType",
    }),
  }),
);
export const relations_payload_folders = relations(
  payload_folders,
  ({ one, many }) => ({
    folder: one(payload_folders, {
      fields: [payload_folders.folder],
      references: [payload_folders.id],
      relationName: "folder",
    }),
    folderType: many(payload_folders_folder_type, {
      relationName: "folderType",
    }),
  }),
);
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    sessionsID: one(sessions, {
      fields: [payload_locked_documents_rels.sessionsID],
      references: [sessions.id],
      relationName: "sessions",
    }),
    accountsID: one(accounts, {
      fields: [payload_locked_documents_rels.accountsID],
      references: [accounts.id],
      relationName: "accounts",
    }),
    verificationsID: one(verifications, {
      fields: [payload_locked_documents_rels.verificationsID],
      references: [verifications.id],
      relationName: "verifications",
    }),
    "admin-invitationsID": one(admin_invitations, {
      fields: [payload_locked_documents_rels["admin-invitationsID"]],
      references: [admin_invitations.id],
      relationName: "admin-invitations",
    }),
    pagesID: one(pages, {
      fields: [payload_locked_documents_rels.pagesID],
      references: [pages.id],
      relationName: "pages",
    }),
    mediaID: one(media, {
      fields: [payload_locked_documents_rels.mediaID],
      references: [media.id],
      relationName: "media",
    }),
    "panter-translateID": one(panter_translate, {
      fields: [payload_locked_documents_rels["panter-translateID"]],
      references: [panter_translate.id],
      relationName: "panter-translate",
    }),
    "payload-foldersID": one(payload_folders, {
      fields: [payload_locked_documents_rels["payload-foldersID"]],
      references: [payload_folders.id],
      relationName: "payload-folders",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);
export const relations_header_nav_items = relations(
  header_nav_items,
  ({ one }) => ({
    _parentID: one(header, {
      fields: [header_nav_items._parentID],
      references: [header.id],
      relationName: "navItems",
    }),
  }),
);
export const relations_header_rels = relations(header_rels, ({ one }) => ({
  parent: one(header, {
    fields: [header_rels.parent],
    references: [header.id],
    relationName: "_rels",
  }),
  pagesID: one(pages, {
    fields: [header_rels.pagesID],
    references: [pages.id],
    relationName: "pages",
  }),
}));
export const relations_header = relations(header, ({ many }) => ({
  navItems: many(header_nav_items, {
    relationName: "navItems",
  }),
  _rels: many(header_rels, {
    relationName: "_rels",
  }),
}));
export const relations_footer_nav_items = relations(
  footer_nav_items,
  ({ one }) => ({
    _parentID: one(footer, {
      fields: [footer_nav_items._parentID],
      references: [footer.id],
      relationName: "navItems",
    }),
  }),
);
export const relations_footer_rels = relations(footer_rels, ({ one }) => ({
  parent: one(footer, {
    fields: [footer_rels.parent],
    references: [footer.id],
    relationName: "_rels",
  }),
  pagesID: one(pages, {
    fields: [footer_rels.pagesID],
    references: [pages.id],
    relationName: "pages",
  }),
}));
export const relations_footer = relations(footer, ({ many }) => ({
  navItems: many(footer_nav_items, {
    relationName: "navItems",
  }),
  _rels: many(footer_rels, {
    relationName: "_rels",
  }),
}));

type DatabaseSchema = {
  enum__locales: typeof enum__locales;
  enum_users_role: typeof enum_users_role;
  enum_admin_invitations_role: typeof enum_admin_invitations_role;
  enum_pages_hero_links_link_type: typeof enum_pages_hero_links_link_type;
  enum_pages_hero_links_link_appearance: typeof enum_pages_hero_links_link_appearance;
  enum_pages_blocks_cta_links_link_type: typeof enum_pages_blocks_cta_links_link_type;
  enum_pages_blocks_cta_links_link_appearance: typeof enum_pages_blocks_cta_links_link_appearance;
  enum_pages_blocks_content_columns_size: typeof enum_pages_blocks_content_columns_size;
  enum_pages_blocks_content_columns_link_type: typeof enum_pages_blocks_content_columns_link_type;
  enum_pages_blocks_content_columns_link_appearance: typeof enum_pages_blocks_content_columns_link_appearance;
  enum_pages_blocks_banner_style: typeof enum_pages_blocks_banner_style;
  enum_pages_hero_type: typeof enum_pages_hero_type;
  enum_pages_status: typeof enum_pages_status;
  enum__pages_v_version_hero_links_link_type: typeof enum__pages_v_version_hero_links_link_type;
  enum__pages_v_version_hero_links_link_appearance: typeof enum__pages_v_version_hero_links_link_appearance;
  enum__pages_v_blocks_cta_links_link_type: typeof enum__pages_v_blocks_cta_links_link_type;
  enum__pages_v_blocks_cta_links_link_appearance: typeof enum__pages_v_blocks_cta_links_link_appearance;
  enum__pages_v_blocks_content_columns_size: typeof enum__pages_v_blocks_content_columns_size;
  enum__pages_v_blocks_content_columns_link_type: typeof enum__pages_v_blocks_content_columns_link_type;
  enum__pages_v_blocks_content_columns_link_appearance: typeof enum__pages_v_blocks_content_columns_link_appearance;
  enum__pages_v_blocks_banner_style: typeof enum__pages_v_blocks_banner_style;
  enum__pages_v_version_hero_type: typeof enum__pages_v_version_hero_type;
  enum__pages_v_version_status: typeof enum__pages_v_version_status;
  enum__pages_v_published_locale: typeof enum__pages_v_published_locale;
  enum_payload_jobs_log_task_slug: typeof enum_payload_jobs_log_task_slug;
  enum_payload_jobs_log_state: typeof enum_payload_jobs_log_state;
  enum_payload_jobs_task_slug: typeof enum_payload_jobs_task_slug;
  enum_payload_folders_folder_type: typeof enum_payload_folders_folder_type;
  enum_header_nav_items_link_type: typeof enum_header_nav_items_link_type;
  enum_footer_nav_items_link_type: typeof enum_footer_nav_items_link_type;
  users_role: typeof users_role;
  users: typeof users;
  sessions: typeof sessions;
  accounts: typeof accounts;
  verifications: typeof verifications;
  admin_invitations: typeof admin_invitations;
  pages_hero_links: typeof pages_hero_links;
  pages_blocks_cta_links: typeof pages_blocks_cta_links;
  pages_blocks_cta: typeof pages_blocks_cta;
  pages_blocks_content_columns: typeof pages_blocks_content_columns;
  pages_blocks_content: typeof pages_blocks_content;
  pages_blocks_media_block: typeof pages_blocks_media_block;
  pages_blocks_banner: typeof pages_blocks_banner;
  pages: typeof pages;
  pages_locales: typeof pages_locales;
  pages_rels: typeof pages_rels;
  _pages_v_version_hero_links: typeof _pages_v_version_hero_links;
  _pages_v_blocks_cta_links: typeof _pages_v_blocks_cta_links;
  _pages_v_blocks_cta: typeof _pages_v_blocks_cta;
  _pages_v_blocks_content_columns: typeof _pages_v_blocks_content_columns;
  _pages_v_blocks_content: typeof _pages_v_blocks_content;
  _pages_v_blocks_media_block: typeof _pages_v_blocks_media_block;
  _pages_v_blocks_banner: typeof _pages_v_blocks_banner;
  _pages_v: typeof _pages_v;
  _pages_v_locales: typeof _pages_v_locales;
  _pages_v_rels: typeof _pages_v_rels;
  media: typeof media;
  panter_translate: typeof panter_translate;
  payload_kv: typeof payload_kv;
  payload_jobs_log: typeof payload_jobs_log;
  payload_jobs: typeof payload_jobs;
  payload_folders_folder_type: typeof payload_folders_folder_type;
  payload_folders: typeof payload_folders;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  header_nav_items: typeof header_nav_items;
  header: typeof header;
  header_rels: typeof header_rels;
  footer_nav_items: typeof footer_nav_items;
  footer: typeof footer;
  footer_rels: typeof footer_rels;
  relations_users_role: typeof relations_users_role;
  relations_users: typeof relations_users;
  relations_sessions: typeof relations_sessions;
  relations_accounts: typeof relations_accounts;
  relations_verifications: typeof relations_verifications;
  relations_admin_invitations: typeof relations_admin_invitations;
  relations_pages_hero_links: typeof relations_pages_hero_links;
  relations_pages_blocks_cta_links: typeof relations_pages_blocks_cta_links;
  relations_pages_blocks_cta: typeof relations_pages_blocks_cta;
  relations_pages_blocks_content_columns: typeof relations_pages_blocks_content_columns;
  relations_pages_blocks_content: typeof relations_pages_blocks_content;
  relations_pages_blocks_media_block: typeof relations_pages_blocks_media_block;
  relations_pages_blocks_banner: typeof relations_pages_blocks_banner;
  relations_pages_locales: typeof relations_pages_locales;
  relations_pages_rels: typeof relations_pages_rels;
  relations_pages: typeof relations_pages;
  relations__pages_v_version_hero_links: typeof relations__pages_v_version_hero_links;
  relations__pages_v_blocks_cta_links: typeof relations__pages_v_blocks_cta_links;
  relations__pages_v_blocks_cta: typeof relations__pages_v_blocks_cta;
  relations__pages_v_blocks_content_columns: typeof relations__pages_v_blocks_content_columns;
  relations__pages_v_blocks_content: typeof relations__pages_v_blocks_content;
  relations__pages_v_blocks_media_block: typeof relations__pages_v_blocks_media_block;
  relations__pages_v_blocks_banner: typeof relations__pages_v_blocks_banner;
  relations__pages_v_locales: typeof relations__pages_v_locales;
  relations__pages_v_rels: typeof relations__pages_v_rels;
  relations__pages_v: typeof relations__pages_v;
  relations_media: typeof relations_media;
  relations_panter_translate: typeof relations_panter_translate;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_jobs_log: typeof relations_payload_jobs_log;
  relations_payload_jobs: typeof relations_payload_jobs;
  relations_payload_folders_folder_type: typeof relations_payload_folders_folder_type;
  relations_payload_folders: typeof relations_payload_folders;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
  relations_header_nav_items: typeof relations_header_nav_items;
  relations_header_rels: typeof relations_header_rels;
  relations_header: typeof relations_header;
  relations_footer_nav_items: typeof relations_footer_nav_items;
  relations_footer_rels: typeof relations_footer_rels;
  relations_footer: typeof relations_footer;
};

declare module "@payloadcms/db-vercel-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
